# Sử dụng base image là Python 3.12 slim
FROM python:3.12.6-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir setuptools

EXPOSE 8000

CMD uvicorn main:app --port=8000 --host=0.0.0.0
